import java.io.*;
public class getEmployee //class getEmployee
{

public getEmployee() //class definition
{
  System.out.print("Please enter the EmployeeID  : ");
  String EmployeeCode = System.console().readLine(); //Getting the EmployeeID...
  retrieveRecord(EmployeeCode); //calling a user defined function to reatrieve the data from the file...
}

private void retrieveRecord(String EmployeeCode) //user defined function to reatrieve the data...
{
  try //try block...
       {

         FileReader fr = new FileReader(".//database//EmployeeData.txt"); //Reading the file from the given location...
         BufferedReader br = new BufferedReader(fr); //storing the content of the file in BufferedReader...
         String Content;//Content is a variable taken to read every line from the file and store it...
         int found = 0; // initializing a varibale found as zero...
         while ((Content = br.readLine()) != null) //Reading the complete file while line is there...
         {
            String EmployeeId = Content.split(",")[0]; //Splitting the details of the line seperated by comma, and storing the Employee Code into a variable named EmployeeId...
            if ( EmployeeCode.toUpperCase().equals(EmployeeId.toUpperCase()) )
            {
            System.out.println("Employee Found !!");
            System.out.println("Employee Details : "+Content); //Printing the Employee details based on EmployeeID...
            found = 1; //initializing 'found' as 1 when Employee details found...
            break; //gets out of the loop...
            }
         }
         if ( found == 0 ) //checking the conditions for found...
         {
         System.out.println("Employee Details Not Found !!"); // printing...
         }
         br.close(); //closing the BufferedReaderobject...
         fr.close(); //closing the fr object...
       }
       catch(Exception ie) //catch block...
         {
            ie.printStackTrace();
         }
    }
}
